### ISSUE TITLE
Add Color to Terminal Output

### ISSUE THREAD

**Issue by wheslleyrimar** [wheslleyrimar/BuildCLI#39]
## Description
Add color to terminal messages to improve readability.
- Display success messages in green, errors in red, and warnings in yellow.

**Comment by omatheusmesmo** [comment]
Olá, Wheslley, espero que esteja bem e um feliz natal!

Iniciei esta Issue hoje e abri um PR, por favor me informe se algo estiver fora do padrão esperado.

PR: https://github.com/wheslleyrimar/BuildCLI/pull/50

Abraços! =)

**Comment by wheslleyrimar** [comment]
Que alegria ler seu comentário, @omatheusmesmo! Seja muito bem-vindo! Estou muito feliz em ter você por aqui.

Vou revisar o PR. Um ponto importante: ele deve ser mergeado na develop, mas ao que parece está apontando a branch main. Poderia verificar?

**Comment by omatheusmesmo** [comment]
> Que alegria ler seu comentário, @omatheusmesmo! Seja muito bem-vindo! Estou muito feliz em ter você por aqui.
> 
> Vou revisar o PR. Um ponto importante: ele deve ser mergeado na develop, mas ao que parece está apontando a branch main. Poderia verificar?
> 


@wheslleyrimar , eu que fico feliz por ter a oportunidade de contribuir.

Ajustei a branch! ☺️
